### ISSUE TITLE
TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by nathfreder** [BoxOfDevs/server-manager#1]
For some reason, it does not work with `nodemon@1.18.4`. It does seem to work when starting using `npm start` or `electron .` though.
```
$ nodemon
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/index.js`
/Users/nathfreder/Coding/server-manager/node_modules/electron-is-dev/index.js:4
const app = electron.app || electron.remote.app;
                                            ^

TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (/Users/nathfreder/Coding/server-manager/node_modules/electron-is-dev/index.js:4:45)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nathfreder/Coding/server-manager/src/index.js:3:23)
    at Module._compile (module.js:653:30)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nathfreder** [comment]
For some reason, I can run `nodemon --exec electron .` and it will work.
```
$ nodemon --exec electron .
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `electron .`
```

**Comment by nathfreder** [comment]
This issue appeared due to failure on my part, it was not executing `npm start` but instead the main file. You can use `nodemon --exec electron .` instead.
